### PR TITLE
Launch rviz within visulization

### PR DESCRIPTION
**Pull request by Peter9606**
1. Add rviz.launch to launch RViz together with visulization
2. Update readme

Signed-off-by: Peter Han <peter.han@intel.com>

### CODE REVIEW

**Comment by Peter9606** [comment]
Fix #2 feature request.

**Comment by Peter9606** [comment]
@yechun1  can you confirm whether this patch can meet your request?

**Comment by congliu0913** [comment]
Can one of the admins verify this patch?

**Comment by yechun1** [comment]
@Peter9606 it's great, thanks.

**Pull request merged**
